# Generated by Django 5.2.13 on 2026-05-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_pedido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='apellido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.CharField(choices=[('retiro', 'Retiro en el local'), ('domicilio', 'Envío a domicilio')], default='retiro', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas_envio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('efectivo', 'Efectivo')], default='transferencia', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='piso_depto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
