# Generated by Django 6.0.4 on 2026-05-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_pedido_apellido_pedido_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
