# Generated by Django 5.2.13 on 2026-05-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_pedido_fecha_pago_pedido_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
