# Generated by Django 5.2.13 on 2026-05-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_oferta_activa_producto_precio_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='numero_cliente',
            field=models.IntegerField(unique=True),
        ),
    ]
