# Generated by Django 5.2.13 on 2026-06-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_perfil_numero_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Lácteos', 'Lácteos'), ('Enlatados', 'Enlatados'), ('Cereales', 'Cereales'), ('Snacks', 'Snacks'), ('Condimentos', 'Condimentos')], max_length=50),
        ),
    ]
