# Generated by Django 5.2.13 on 2026-06-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_imagen_base64_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
