# Generated by Django 5.2.13 on 2026-06-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_clienteextra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClienteExtra',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Lácteos', 'Lácteos'), ('Aperitivos', 'Aperitivos'), ('Almacén', 'Almacén'), ('Bebidas Alcohólicas', 'Bebidas Alcohólicas'), ('Limpieza', 'Limpieza'), ('Bebidas', 'Bebidas')], max_length=50),
        ),
    ]
