# Generated by Django 5.2.13 on 2026-06-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_cantidad_mayorista_and_more'),
        ('productos', '0012_delete_clienteextra_alter_producto_categoria'),
    ]

    operations = [
    ]
