# Generated by Django 5.2.13 on 2026-06-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_merge_20260622_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mp_payment_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='mp_preference_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pagado',
        ),
    ]
