# Generated by Django 5.2.13 on 2026-06-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_remove_pedido_fecha_pago_remove_pedido_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Lácteos', 'Lácteos'), ('Gaseosas', 'Gaseosas'), ('Aperitivos', 'Aperitivos'), ('Almacén', 'Almacén'), ('Bebidas Alcohólicas', 'Bebidas Alcohólicas'), ('Limpieza', 'Limpieza')], max_length=50),
        ),
    ]
